# Application Settings
spring:
  application:
    name: "dining-room-gateway"
  cloud:
    gateway:
      routes:
       - id: dining-room-warehouse
         uri: lb://dining-room-warehouse
         predicates:
          - Path=/stocks/**

       - id: dining-room-catalog
         uri: lb://dining-room-catalog
         predicates:
          - Path=/brands/**

       - id: dining-room-catalog
         uri: lb://dining-room-catalog
         predicates:
           - Path=/products/**

       - id: dining-room-cart
         uri: lb://dining-room-cart
         predicates:
           - Path=/orders/**

       - id: dining-room-cart
         uri: lb://dining-room-cart
         predicates:
           - Path=/itemsOrder/**

       - id: dining-room-user-registry
         uri: lb://dining-room-user-registry
         predicates:
           - Path=/clients/**
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST_EUREKA}:${DB_PORT_EUREKA}/eureka/