# Application Settings
spring:
  application:
    name: "dining-room-gateway"
  cloud:
    gateway:
      routes:
       - id: dining-room-warehouse
         uri: lb://dining-room-warehouse
         predicates:
          - Path=/stocks/**
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/