# Application Settings
spring:
  application:
    name: "dining-room-gateway"
cloud:
  gateway:
    routes:
      - id: dining-room-catalog
        uri: lb://dining-room-catalog
        predicates:
          - Path=/brands/**
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaulZone: http://localhost:8761/eureka/